nameOverride: nginx-ingress

controller:
  kind: DaemonSet

  config:
    proxy-protocol: "true"
    real-ip-header: "proxy_protocol"
    set-real-ip-from: "0.0.0.0/0"
    use-forwarded-headers: "true"
    # for aws-nlb
    ssl-redirect: "false" # we use `special` port to control ssl redirection
    server-snippet: |
      listen 8000;
      if ( $server_port = 80 ) {
         return 308 https://$host$request_uri;
      }

  containerPort:
    http: 80
    https: 443
    special: 8000

  service:
    targetPorts:
      http: http
      https: special # https, special

    annotations:
      external-dns.alpha.kubernetes.io/hostname: ""
      # external-dns.alpha.kubernetes.io/ttl: "300"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp" # http, tcp
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ""
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

  stats:
    enabled: true

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus-operator

  tolerations:
    - key: node-role
      operator: Equal
      value: ops
      effect: NoSchedule

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role
                operator: In
                values:
                  - svc
