nameOverride: docker-registry

podAnnotations:
  # cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
  iam.amazonaws.com/role: "eks-demo-bucket"

storage: s3

s3:
  region: "ap-northeast-2"
  bucket: "eks-demo-registry-demo"
  encrypt: "false"
  secure: "false"

secrets:
  haSharedSecret: "secret-string-287463"
  s3:
    accessKey: ""
    secretKey: ""

ingress:
  enabled: true
  annotations:
    # cert-manager.io/cluster-issuer: "letsencrypt-issuer"
    ingress.kubernetes.io/proxy-body-size: "0"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/whitelist-source-range: "0.0.0.0/0"
  hosts:
    - "registry.bruce.spic.me"
  path: /
  # tls:
  #   - secretName: docker-registry-tls
  #     hosts:
  #       - "registry.bruce.spic.me"
