nameOverride: harbor

expose:
  type: ingress
  ingress:
    hosts:
      core: "harbor-core.bruce.spic.me"
      notary: "harbor-notary.bruce.spic.me"
    annotations:
      # cert-manager.io/cluster-issuer: "letsencrypt-issuer"
      ingress.kubernetes.io/proxy-body-size: "0"
      ingress.kubernetes.io/ssl-redirect: "true"
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      # nginx.ingress.kubernetes.io/whitelist-source-range: "0.0.0.0/0"
  # tls:
  #   enabled: true
  #   secretName: "harbor-core-tls"
  #   notarySecretName: "harbor-notary-tls"

externalURL: "https://harbor-core.bruce.spic.me"

harborAdminPassword: "password"

core:
  podAnnotations:
    # cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    iam.amazonaws.com/role: "eks-demo-bucket"

registry:
  podAnnotations:
    # cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    iam.amazonaws.com/role: "eks-demo-bucket"

chartmuseum:
  podAnnotations:
    # cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    iam.amazonaws.com/role: "eks-demo-bucket"

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      storageClass: default
    chartmuseum:
      storageClass: default
    jobservice:
      storageClass: default
    database:
      storageClass: default
    redis:
      storageClass: default
    trivy:
      storageClass: default
  imageChartStorage:
    s3:
      region: "ap-northeast-2"
      bucket: "eks-demo-harbor-demo"
